version: "3"
services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: ${PROJECT_NAME}_webserver
    restart: 'always'
    expose:
      - "9000" #expose port for xdebug
    ports:
      - ${HOST_PORT}:80
      - ${SECURE_HOST_PORT}:443
    links:
      - mysql
      - redis
    volumes:
      - ${DOCUMENT_ROOT-./www}:/usr/share/nginx/html
      - ${VHOSTS_DIR-./config/nginx/sites-enabled}:/etc/nginx/sites-enabled
      - ${PHP_INI-./config/php/php.ini}:/etc/php/7.3/fpm/conf.d/php.ini
      - ${LOG_DIR-./logs/nginx}:/var/log/nginx
  mysql:
    build:
      context: "./bin/${DATABASE}"
    container_name: ${PROJECT_NAME}_mysql
    restart: 'always'
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    build:
      context: ./bin/phpmyadmin
    container_name: ${PROJECT_NAME}_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '8080:80'
    volumes:
      - /sessions
  redis:
    container_name: ${PROJECT_NAME}_redis
    build:
      context: ./bin/redis
    ports:
      - ${REDIS_PORT}:6379
  blackfire:
    container_name: ${PROJECT_NAME}_blackfire
    build:
      context: ./bin/blackfire
    ports: ["8707"]
    environment:
      BLACKFIRE_SERVER_ID: "${BLACKFIRE_SERVER_ID}"
      BLACKFIRE_SERVER_TOKEN: "${BLACKFIRE_SERVER_TOKEN}"
      BLACKFIRE_CLIENT_ID: " ${BLACKFIRE_CLIENT_ID}"
      BLACKFIRE_CLIENT_TOKEN:  "${BLACKFIRE_CLIENT_TOKEN}"